# Nocturne TUI Menu Configuration - Key-based structure
[menu]
title = "Nocturne Main Menu"
description = "Nocturne desktop environment management"
shell = "bash"

# ASCII Art Configuration (max 8 rows)
ascii_art = [
    "███    ██  ██████   ██████ ████████ ██    ██ ██████  ███    ██ ███████",
    "████   ██ ██    ██ ██         ██    ██    ██ ██   ██ ████   ██ ██     ",
    "██ ██  ██ ██    ██ ██         ██    ██    ██ ██████  ██ ██  ██ █████  ",
    "██  ██ ██ ██    ██ ██         ██    ██    ██ ██   ██ ██  ██ ██ ██     ",
    "██   ████  ██████   ██████    ██     ██████  ██   ██ ██   ████ ███████",
]

[menu.install]
type = "submenu"
name = "Installation"
description = "Install Nocturne components"

[menu.install.compositor]
type = "action"
name = "Install Compositor"
description = "Install the Nocturne window compositor"
command = "echo 'Installing compositor...'"

[menu.install.browser]
type = "selector"
name = "Select Browser to Install"
description = "Choose which browser to install"
options = ["firefox", "chromium:Open source chromium", "brave", "opera", "zen", "vivaldi", "chrome:Google chrome"]
default = "firefox"
variable = "BROWSER"

[menu.install.packages]
type = "multiple_selection"
name = "Select Additional Packages"
description = "Choose optional packages to install"
options = ["git", "vim", "neovim:Advanced vim-based editor", "zsh", "tmux:Terminal multiplexer", "curl", "wget:HTTP retrieval tool"]
install_key = "PACKAGES"

[menu.install.install_packages]
type = "action"
name = "Install Selected Packages"
description = "Install the chosen additional packages"
command = "echo 'Installing packages...'; for pkg in ${PACKAGES}; do echo 'Installing $pkg...'; sudo pacman -S $pkg; done"

[menu.install.install_browser]
type = "action"
name = "Install Selected Browser"
description = "Install the chosen browser"
command = "echo 'Installing ${BROWSER}...'; sudo pacman -S ${BROWSER}"

[menu.install.theme]
type = "action"
name = "Install Themes"
description = "Install Nocturne theme packages"
command = "echo 'Installing themes...'"

[menu.install.execute]
type = "action"
name = "execute installation"
description = "Execute the installer based on all configured options"
command = "/home/adary/work/nocturne-tui/config/one.sh"

[menu.configuration]
type = "submenu"
name = "Configuration"
description = "Configure Nocturne settings"

[menu.configuration.theme_selector]
type = "selector"
name = "Select Theme"
description = "Choose your desktop theme"
options = ["dark", "light", "nocturne", "purple", "blue"]
default = "nocturne"
variable = "THEME"

[menu.configuration.apply_theme]
type = "action"
name = "Apply Selected Theme"
description = "Apply the chosen theme"
command = "echo 'Applying ${THEME} theme...'; nocturne-theme set ${THEME}"

[menu.configuration.keybinds]
type = "action"
name = "Key Bindings"
description = "Configure keyboard shortcuts"
command = "echo 'Configuring keybinds...'"

[menu.system]
type = "submenu"
name = "System Info"
description = "View system information"

[menu.system.cpu]
type = "action"
name = "CPU Info"
description = "Display CPU information"
command = "lscpu"

[menu.system.memory]
type = "action"
name = "Memory Usage"
description = "Show memory usage statistics"
command = "free -h"

[menu.system.disk]
type = "action"
name = "Disk Usage"
description = "Display disk space usage"
command = "df -h"

[menu.network]
type = "submenu"
name = "Network Tools"
description = "Network diagnostics and monitoring"

[menu.network.interfaces]
type = "action"
name = "Network Interfaces"
description = "Show network interface configuration"
command = "ip addr show"

[menu.network.ping]
type = "submenu"
name = "Ping Tests"
description = "Network connectivity tests"

[menu.network.ping.google]
type = "action"
name = "Ping Google (300 times)"
description = "Long-running test - press 's' to show/hide output"
command = "ping -c 30 8.8.8.8"

[menu.network.ping.gateway]
type = "action"
name = "Ping Gateway"
description = "Test connectivity to local gateway"
command = "ping -c 4 $(ip route | grep default | awk '{print $3}' | head -1)"

[menu.network.test_ctrl_c]
type = "action"
name = "Test Ctrl+C Handling"
description = "Test script to verify Ctrl+C stops commands properly"
command = "./test-ctrl-c.sh"

[menu.network.debug_pid]
type = "action"
name = "Debug PID Info"
description = "Shows PID relationships for debugging"
command = "./debug-pid.sh"

[menu.network.simple_test]
type = "action"
name = "Simple Test (30s)"
description = "Simple 30-second test for Ctrl+C"
command = "./simple-test.sh"

[menu.about]
type = "action"
name = "About Nocturne"
description = ""
command = "cat ~/.config/nwizard/data/disclaimer"
