[menu]
title = "Nocturne Status Demo"
description = "Testing dynamic status messages"

ascii_art = [
    "███    ██  ██████   ██████ ████████ ██    ██ ██████  ███    ██ ███████",
    "████   ██ ██    ██ ██         ██    ██    ██ ██   ██ ████   ██ ██     ",
    "██ ██  ██ ██    ██ ██         ██    ██    ██ ██████  ██ ██  ██ █████  ",
    "██  ██ ██ ██    ██ ██         ██    ██    ██ ██   ██ ██  ██ ██ ██     ",
    "██   ████  ██████   ██████    ██     ██████  ██   ██ ██   ████ ███████",
]

[menu.status_demo]
type = "action"
name = "Status Demo"
description = "Demo script with dynamic status messages"
command = "./test_status_demo.sh"
nwizard_status = "[STATUS_DEMO]"

[menu.traditional]
type = "action"
name = "Traditional Command"
description = "Command without status messages (shows default 'Processing command...')"
command = "echo 'This is a traditional command'; sleep 3; echo 'Command finished without status updates'"

[menu.different_prefix]
type = "action"
name = "Different Prefix Demo"
description = "Script using a different status prefix"
command = "echo '[CUSTOM_PREFIX] Custom status message'; sleep 2; echo 'Regular output line'; echo '[CUSTOM_PREFIX] Another status'; sleep 1; echo 'Final output'"
nwizard_status = "[CUSTOM_PREFIX]"

[menu.mixed_output]
type = "action"  
name = "Mixed Output Demo"
description = "Script that mixes status messages with regular output"
command = "echo '[STATUS_DEMO] Starting mixed demo...'; echo 'This is regular output that will appear in the output buffer'; echo '[STATUS_DEMO] Processing data...'; echo 'More regular output here'; echo '[STATUS_DEMO] Almost done...'; echo 'Final regular output'; sleep 1"
nwizard_status = "[STATUS_DEMO]"

