#!/bin/bash
echo "=== nwiz Features Demonstrated ==="
echo ""
echo "1. Menu Types:"
echo "   - action: Execute shell scripts and commands"
echo "   - selector: Single choice selection with install_key"
echo "   - multiple_selection: Multi-choice selection with install_key"
echo "   - submenu: Nested menu navigation"
echo ""
echo "2. Status Messages:"
echo "   - Real-time command progress indicators"
echo "   - Custom status prefixes for different operations"
echo "   - Mixed status and regular output handling"
echo "   - Status message history in spinner view"
echo ""
echo "3. Configuration:"
echo "   - ASCII art headers for branding"
echo "   - Variable persistence using install.toml"
echo "   - Configuration loading with --config-options"
echo "   - Custom shell selection per menu"
echo ""
echo "4. Advanced Features:"
echo "   - Multi-level menu nesting (unlimited depth)"
echo "   - Complex workflows and integration patterns"
echo "   - Disclaimer dialogs for important operations"
echo "   - Shell script integration best practices"
sleep 1