#!/bin/bash
echo "=== nwiz Navigation Help ==="
echo ""
echo "Keyboard Controls:"
echo "↑/↓ Arrow Keys  - Navigate menu items"
echo "Enter           - Select item or execute command"
echo "Escape          - Go back to parent menu"
echo "Ctrl+C          - Exit application"
echo ""
echo "During Command Execution:"
echo "Page Up/Down    - Scroll output"
echo "Escape          - Return to menu"
echo "Ctrl+C          - Terminate running command"
echo ""
echo "Menu Features:"
echo "- Real-time status updates with custom prefixes"
echo "- Scrollable output for long command results"
echo "- Command success/failure indication"
echo "- Variable persistence across commands using install.toml"
echo "- Shell script execution with configuration loading"
echo ""
echo "Best Practices:"
echo "- Use shell scripts instead of direct commands"
echo "- Load configuration with 'eval \$(nwiz --config-options)'"
echo "- Use meaningful status prefixes for better UX"
sleep 1