# Nocturne Installation Configuration
# This file stores selection values from multiple selection and selector menu items

[install]
theme = "dark"
dev_tools = []
editor_type = "vim"
shell_type = "bash"
project_lang = "javascript"
project_features = []
