# Nocturne Installation Configuration
# This file stores selection values from multiple selection and selector menu items

theme = "dark"
dev_tools = ["git", "nodejs", "curl"]
editor_type = "nano"
shell_type = "zsh"
project_lang = "python"
project_features = ["testing", "linting", "docker", "ci", "docs"]
